# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chubbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chubbie',
            name='image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
